steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE_URI}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE_URI}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_IMAGE_URI}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=3000
      - --service-account=${_SERVICE_ACCOUNT}
      - --concurrency=${_CONCURRENCY}
      - --cpu=${_CPU}
      - --memory=${_MEMORY}
      - --timeout=${_TIMEOUT}
      - --cpu-throttling
      - --no-cpu-boost
      - --min-instances=0
      - --max-instances=${_MAX_INSTANCES}
      - --set-env-vars=^|^NODE_ENV=production|SHOPIFY_BILLING_TEST=false|SHOPIFY_APP_URL=${_SHOPIFY_APP_URL}|SCOPES=${_SCOPES}|SESSION_STORAGE_BACKEND=firestore|FIRESTORE_SESSION_COLLECTION=${_FIRESTORE_SESSION_COLLECTION}
      - --set-secrets=SHOPIFY_API_KEY=${_SHOPIFY_API_KEY_SECRET}:latest,SHOPIFY_API_SECRET=${_SHOPIFY_API_SECRET_SECRET}:latest

images:
  - ${_IMAGE_URI}

substitutions:
  _SERVICE_NAME: discount-app
  _REGION: europe-north1
  _SERVICE_ACCOUNT: discount-app-run@discount-494316.iam.gserviceaccount.com
  _CONCURRENCY: '1'
  _CPU: '0.5'
  _MEMORY: 512Mi
  _TIMEOUT: 60s
  _MAX_INSTANCES: '3'
  _IMAGE_URI: europe-north1-docker.pkg.dev/discount-494316/cloud-run-source-deploy/discount-app
  _SHOPIFY_APP_URL: https://discount-app-437971048935.europe-north1.run.app
  _FIRESTORE_SESSION_COLLECTION: shopify_sessions
  _SCOPES: read_discounts,write_discounts,write_products,read_shipping,read_markets,write_metaobjects,write_metaobject_definitions
  _SHOPIFY_API_KEY_SECRET: shopify-api-key
  _SHOPIFY_API_SECRET_SECRET: shopify-api-secret
